#!/bin/bash

cwd="$(cd "$(dirname "$0")" && pwd)"

# Script's color palette
reset="\033[0m"
highlight="\033[41m\033[97m"
dot="\033[33m▸ $reset"
dim="\033[2m"
bold="\033[1m"

headline() {
    printf "${highlight} %s ${reset}\n" "$@"
}

chapter() {
    echo -e "${highlight} $((count++)).) $@ ${reset}\n"
}

# Prints out a step, if last parameter is true then without an ending newline
step() {
    if [ $# -eq 1 ]
    then echo -e "${dot}$@"
    else echo -ne "${dot}$@"
    fi
}

run() {
    echo -e "${dim}▹ $@ $reset"
    eval $@
    echo ""
}

step "Atom packages/themes\n"

for package in $(<$cwd/.stack/atom); do
    if [ ! -d ~/.atom/packages/$package ]; then
        run apm install $package
    fi
done


step "Atom preferences\n"
run mkdir -pv ~/.atom
run ln -sfv $cwd/.atom/config.cson ~/.atom
run ln -sfv $cwd/.atom/keymap.cson ~/.atom
run ln -sfv $cwd/.atom/snippets.cson ~/.atom
run ln -sfv $cwd/.atom/toolbar.cson ~/.atom
run ln -sfv $cwd/.atom/styles.less ~/.atom
